sonar.projectKey=ekanshchauhan
sonar.organization=EKANSHCHAUHAN
sonar.host.url=https://sonarcloud.io
sonar.login=${717cd4c6b4eec2e3783f2ee82339ee801d2bb311}
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8

